# This is a basic workflow
name: Decision tree to binary

# Controls when the workflow will run
on:
  # Triggers the workflow on push only for ipynb modifications
  pull_request:
    types:
      - opened
      - reopened
        # We will disable 'syncronize' option, since we prefer to start GA ONLY manually by opening PRs.
        # - synchronize
    branches:
      - main
    paths:
      - 'model-tree-classifier/decision-tree-classifier.ipynb'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    # Checks if notebook output has been cleaned
    - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupytext pipreqs

    # It would not be necessary to specify $GITHUB_WORKSPACE since it is the current folder
    - name: Convert notebook to py script amd generate requirements
      run: |
        jupytext --to py $GITHUB_WORKSPACE/model-tree-classifier/decision-tree-classifier.ipynb -o $GITHUB_WORKSPACE/model-tree-classifier/decision-tree-classifier.py
        pipreqs --force $GITHUB_WORKSPACE/model-tree-classifier/

    # WARNING: It will probably fail if decision-tree-classifier.ipynb is renamed without further changes
    # WARNING: At this time, .py and reqs are commited to Merge commit, but it can be modified under actions/checkout@v2
    # so the commit goes to release/xxx branch
    - name: Commit new py executable if necessary
      run:  |
        # This "if" is set in order there is a new PR with changes on IPYNB but not on PY.
        # We need to add our files of interest so git diff can work on them both if they have been modified or newly created.
        git add $GITHUB_WORKSPACE/model-tree-classifier/decision-tree-classifier.py $GITHUB_WORKSPACE/model-tree-classifier/requirements.txt
        if ! git diff --exit-code model-tree-classifier/decision-tree-classifier.py; then
          git config --global user.name 'roldanx'
          git config --global user.email 'roldanx@github.com'
          git commit -m "Update executable and generate requirements"
          git fetch origin ${{ github.head_ref }}
          git push origin ${{ github.head_ref }}
        else
          echo "NO changes to be commited in decision-tree-classifier.py"
        fi
