# This is a basic workflow to help you get started with Actions

name: Jupytext

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupytext
        
    # It is not necessary to specify $GITHUB_WORKSPACE since it is the current folder
    - name: Convert notebook to py script
      run: |
        jupytext --to py decision-tree-classifier-tutorial.ipynb -o $GITHUB_WORKSPACE/python/decision-tree-classifier.py 

    - name: Commit new py executable
      run:  |
        git remote set-url origin ${{ secrets.ssh }}
        git add . $GITHUB_WORKSPACE/python/decision-tree-classifier.py
        git commit -m "Update executable"
        git fetch origin main
        git push origin HEAD:main
