# This is a basic workflow to help you get started with Actions

name: Registry Docker build

# Controls when the workflow will run
on:
  # Triggers the workflow on push only for ipynb modifications
  push:
    branches: [ main ]
    paths:
      - 'postgresql'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2
        
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: roldanx/postgresql-mlflow
        registry: docker.io
        dockerfile: postgresql/Dockerfile
        directory: postgresql
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
